// data.jsx — mock dataset of files, sessions, days
// All content is realistic for the 3 storyboard scenarios + everyday usage.

const TAGS = {
  // money
  comprovante:     { color: 'var(--tag-money)', bg: 'var(--tag-money-bg)' },
  fatura:          { color: 'var(--tag-money)', bg: 'var(--tag-money-bg)' },
  recibo:          { color: 'var(--tag-money)', bg: 'var(--tag-money-bg)' },
  // time
  maio:            { color: 'var(--tag-time)',  bg: 'var(--tag-time-bg)' },
  abril:           { color: 'var(--tag-time)',  bg: 'var(--tag-time-bg)' },
  // doc
  artigo:          { color: 'var(--tag-doc)',   bg: 'var(--tag-doc-bg)' },
  artigo_academico:{ color: 'var(--tag-doc)',   bg: 'var(--tag-doc-bg)' },
  estudos:         { color: 'var(--tag-doc)',   bg: 'var(--tag-doc-bg)' },
  pesquisa:        { color: 'var(--tag-doc)',   bg: 'var(--tag-doc-bg)' },
  notas:           { color: 'var(--tag-doc)',   bg: 'var(--tag-doc-bg)' },
  anotacoes:       { color: 'var(--tag-doc)',   bg: 'var(--tag-doc-bg)' },
  // image
  foto:            { color: 'var(--tag-img)',   bg: 'var(--tag-img-bg)' },
  print:           { color: 'var(--tag-img)',   bg: 'var(--tag-img-bg)' },
  grafico_dados:   { color: 'var(--tag-img)',   bg: 'var(--tag-img-bg)' },
  // place / topic
  energia:         { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  saude:           { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  saude_2024:      { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  laboratorio:     { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  exame_sangue:    { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  hci:             { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  ux:              { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  viagem:          { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
  receita:         { color: 'var(--tag-place)', bg: 'var(--tag-place-bg)' },
};

const tagMeta = (name) => TAGS[name] || { color: 'var(--ink-2)', bg: 'var(--bg-chip)' };

// Files keyed by id ─────────────────────────────────────
const FILES = [
  // ─── HOJE — Sessão 14h–17h: Pesquisa Acadêmica (Cenário 2) ───
  {
    id: 'f-101',
    name: 'Donald Norman — User-Centered Design.pdf',
    kind: 'PDF · 14 páginas',
    size: '2.1 MB',
    time: '14:08',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Baixado de scholar.google.com',
    summary: 'Capítulo seminal sobre os princípios de design centrado no usuário, com foco em affordances, mapeamentos e feedback visíveis.',
    tags: ['artigo_academico', 'estudos', 'ux'],
    suggested: ['hci'],
    approved: true,
    thumb: { kind: 'doc', title: 'User-Centered Design', subtitle: 'D. Norman · 1986', accent: 'var(--accent-sky)' },
  },
  {
    id: 'f-102',
    name: 'Nielsen — 10 Usability Heuristics.pdf',
    kind: 'PDF · 9 páginas',
    size: '1.4 MB',
    time: '14:21',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Baixado de nngroup.com',
    summary: 'As dez heurísticas clássicas para avaliação de usabilidade de interfaces.',
    tags: ['artigo_academico', 'estudos'],
    suggested: ['ux', 'hci'],
    approved: true,
    thumb: { kind: 'doc', title: '10 Usability Heuristics', subtitle: 'J. Nielsen', accent: 'var(--accent-sky)' },
  },
  {
    id: 'f-103',
    name: 'gráfico — adoção de busca semântica.png',
    kind: 'Imagem · 1280×720',
    size: '184 KB',
    time: '15:02',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Salvo de statista.com',
    summary: 'Gráfico de linha mostrando adoção de busca semântica em ferramentas de produtividade entre 2019 e 2025.',
    tags: ['grafico_dados', 'pesquisa'],
    suggested: ['ux'],
    approved: true,
    thumb: { kind: 'chart', kind2: 'line' },
  },
  {
    id: 'f-104',
    name: 'gráfico de barras — tempo gasto buscando arquivos.png',
    kind: 'Imagem · 1024×640',
    size: '142 KB',
    time: '15:18',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Salvo de mckinsey.com',
    summary: 'Comparativo do tempo médio que profissionais de conhecimento gastam por semana procurando arquivos em diferentes paradigmas de organização.',
    tags: ['grafico_dados', 'pesquisa'],
    suggested: [],
    approved: true,
    thumb: { kind: 'chart', kind2: 'bar' },
  },
  {
    id: 'f-105',
    name: 'Card Sorting — Estudo de Tags.pdf',
    kind: 'PDF · 22 páginas',
    size: '3.4 MB',
    time: '15:33',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Baixado de acm.org',
    summary: 'Metodologia para inferir taxonomias mentais usuárias a partir de exercícios de card sorting.',
    tags: ['artigo_academico', 'pesquisa'],
    suggested: ['ux'],
    approved: false,
    thumb: { kind: 'doc', title: 'Card Sorting Study', subtitle: 'ACM CHI 2021', accent: 'var(--accent-sky)' },
  },
  {
    id: 'f-106',
    name: 'Affordances Revisitadas.pdf',
    kind: 'PDF · 11 páginas',
    size: '1.8 MB',
    time: '15:55',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Baixado de jstor.org',
    summary: 'Reinterpretação contemporânea do conceito de affordance no design de interfaces digitais.',
    tags: ['artigo_academico', 'estudos'],
    suggested: ['ux', 'hci'],
    approved: false,
    thumb: { kind: 'doc', title: 'Affordances Revisitadas', subtitle: 'McGrenere · 2000', accent: 'var(--accent-sky)' },
  },
  {
    id: 'f-107',
    name: 'anotações — IHC aula 8.txt',
    kind: 'Texto · 380 palavras',
    size: '12 KB',
    time: '16:42',
    day: 'hoje',
    sessionId: 'pesquisa-tarde',
    source: 'Criado no app',
    summary: 'Resumo pessoal das leituras da tarde: princípios de Norman, heurísticas de Nielsen e como aplicar na busca semântica.',
    tags: ['anotacoes', 'estudos', 'hci'],
    suggested: [],
    approved: true,
    thumb: { kind: 'note', headline: 'Como o usuário lembra de um arquivo? Por contexto, não por nome.' },
  },

  // ─── HOJE — Sessão 11h: Exames médicos (Cenário 3) ───
  {
    id: 'f-201',
    name: 'doc_lab_01.pdf',
    kind: 'PDF · 2 páginas',
    size: '420 KB',
    time: '11:14',
    day: 'hoje',
    sessionId: 'exames-manha',
    source: 'Arrastado do navegador',
    summary: 'Hemograma completo — Laboratório São Lucas. Resultados dentro dos parâmetros de referência.',
    tags: [],
    suggested: ['exame_sangue', 'laboratorio', 'saude_2024'],
    approved: false,
    thumb: { kind: 'doc', title: 'Hemograma Completo', subtitle: 'Lab. São Lucas', accent: 'var(--accent-terra)' },
  },
  {
    id: 'f-202',
    name: 'doc_lab_02.pdf',
    kind: 'PDF · 1 página',
    size: '210 KB',
    time: '11:14',
    day: 'hoje',
    sessionId: 'exames-manha',
    source: 'Arrastado do navegador',
    summary: 'Glicemia de jejum — 92 mg/dL.',
    tags: [],
    suggested: ['exame_sangue', 'laboratorio', 'saude_2024'],
    approved: false,
    thumb: { kind: 'doc', title: 'Glicemia de Jejum', subtitle: 'Lab. São Lucas', accent: 'var(--accent-terra)' },
  },
  {
    id: 'f-203',
    name: 'doc_lab_03.pdf',
    kind: 'PDF · 3 páginas',
    size: '480 KB',
    time: '11:14',
    day: 'hoje',
    sessionId: 'exames-manha',
    source: 'Arrastado do navegador',
    summary: 'Perfil lipídico completo — colesterol total, HDL, LDL e triglicerídeos.',
    tags: [],
    suggested: ['exame_sangue', 'laboratorio', 'saude_2024'],
    approved: false,
    thumb: { kind: 'doc', title: 'Perfil Lipídico', subtitle: 'Lab. São Lucas', accent: 'var(--accent-terra)' },
  },
  {
    id: 'f-204',
    name: 'doc_lab_04.pdf',
    kind: 'PDF · 2 páginas',
    size: '380 KB',
    time: '11:14',
    day: 'hoje',
    sessionId: 'exames-manha',
    source: 'Arrastado do navegador',
    summary: 'Vitamina D — 32 ng/mL.',
    tags: [],
    suggested: ['laboratorio', 'saude_2024'],
    approved: false,
    thumb: { kind: 'doc', title: 'Dosagem Vitamina D', subtitle: 'Lab. São Lucas', accent: 'var(--accent-terra)' },
  },
  {
    id: 'f-205',
    name: 'doc_lab_05.pdf',
    kind: 'PDF · 1 página',
    size: '180 KB',
    time: '11:15',
    day: 'hoje',
    sessionId: 'exames-manha',
    source: 'Arrastado do navegador',
    summary: 'TSH — 1.8 µIU/mL.',
    tags: [],
    suggested: ['laboratorio', 'saude_2024'],
    approved: false,
    thumb: { kind: 'doc', title: 'TSH', subtitle: 'Lab. São Lucas', accent: 'var(--accent-terra)' },
  },

  // ─── ONTEM — Cenário 1: O comprovante perdido ───
  {
    id: 'f-301',
    name: 'IMG_20240518_1030.png',
    kind: 'Imagem · 1080×1920',
    size: '720 KB',
    time: '10:32',
    day: 'ontem',
    dayLabel: '18 de maio',
    sessionId: 'manha-celular',
    source: 'Captura de tela · iPhone',
    summary: 'Print do comprovante de pagamento da fatura de energia — ENEL · valor R$ 184,72 · vencimento 20/05/2024.',
    tags: ['comprovante', 'maio', 'energia', 'fatura'],
    suggested: [],
    approved: true,
    thumb: { kind: 'receipt', company: 'ENEL · Energia', total: 'R$ 184,72', ocr: true },
  },
  {
    id: 'f-302',
    name: 'IMG_20240518_1031.png',
    kind: 'Imagem · 1080×1920',
    size: '650 KB',
    time: '10:34',
    day: 'ontem',
    sessionId: 'manha-celular',
    source: 'Captura de tela',
    summary: 'Print da tela de confirmação do app bancário.',
    tags: ['print', 'comprovante'],
    suggested: [],
    approved: true,
    thumb: { kind: 'photo', palette: ['oklch(0.7 0.12 145)', 'oklch(0.85 0.08 200)', 'oklch(0.95 0.02 200)'] },
  },
  {
    id: 'f-303',
    name: 'IMG_20240518_1422.png',
    kind: 'Imagem · 4032×3024',
    size: '3.8 MB',
    time: '14:22',
    day: 'ontem',
    sessionId: 'tarde-quadro',
    source: 'Câmera · iPhone',
    summary: 'Foto do quadro branco da reunião de planejamento — fluxograma de telas e anotações em vermelho.',
    tags: ['anotacoes', 'foto'],
    suggested: ['ux'],
    approved: true,
    thumb: { kind: 'whiteboard' },
  },
  {
    id: 'f-304',
    name: 'IMG_20240518_1830.png',
    kind: 'Imagem · 4032×3024',
    size: '4.1 MB',
    time: '18:30',
    day: 'ontem',
    sessionId: 'tarde-quadro',
    source: 'Câmera',
    summary: 'Foto do pôr do sol no caminho de casa.',
    tags: ['foto'],
    suggested: ['viagem'],
    approved: true,
    thumb: { kind: 'photo', palette: ['oklch(0.78 0.16 50)', 'oklch(0.65 0.12 25)', 'oklch(0.5 0.08 280)'] },
  },

  // ─── SEMANA PASSADA ───
  {
    id: 'f-401',
    name: 'Receita médica — Dra. Carolina.pdf',
    kind: 'PDF · 1 página',
    size: '140 KB',
    time: '09:15',
    day: 'semana',
    dayLabel: '12 de maio',
    sessionId: 'consulta',
    source: 'Email — Dra. Carolina',
    summary: 'Prescrição de vitamina D 50.000 UI semanal por 8 semanas.',
    tags: ['receita', 'saude_2024'],
    suggested: [],
    approved: true,
    thumb: { kind: 'doc', title: 'Receita Médica', subtitle: 'Dra. Carolina · CRM 12345', accent: 'var(--accent-moss)' },
  },
  {
    id: 'f-402',
    name: 'planilha — gastos mensais.xlsx',
    kind: 'Planilha · 4 abas',
    size: '88 KB',
    time: '20:42',
    day: 'semana',
    dayLabel: '10 de maio',
    sessionId: 'financas',
    source: 'Editado',
    summary: 'Controle financeiro pessoal — abas de receitas, despesas fixas, variáveis e investimentos.',
    tags: ['fatura'],
    suggested: [],
    approved: true,
    thumb: { kind: 'sheet' },
  },
];

// Sessions metadata ─────────────────────────────────────
const SESSIONS = {
  'pesquisa-tarde': {
    id: 'pesquisa-tarde',
    label: 'Sessão de Pesquisa',
    timeRange: '14h — 17h',
    day: 'hoje',
    summary: 'Pesquisa acadêmica sobre design centrado no usuário e usabilidade.',
    autoTags: ['artigo_academico', 'estudos', 'ux'],
  },
  'exames-manha': {
    id: 'exames-manha',
    label: 'Caixa de Entrada',
    timeRange: '11h',
    day: 'hoje',
    summary: '5 PDFs arrastados do navegador — exames laboratoriais.',
    autoTags: ['laboratorio', 'saude_2024'],
  },
  'manha-celular': {
    id: 'manha-celular',
    label: 'Pagamentos',
    timeRange: '10h — 11h',
    day: 'ontem',
    summary: 'Pagamento de contas pelo aplicativo bancário.',
    autoTags: ['comprovante', 'maio'],
  },
  'tarde-quadro': {
    id: 'tarde-quadro',
    label: 'Reunião + Casa',
    timeRange: '14h — 19h',
    day: 'ontem',
    summary: 'Reunião de planejamento e fim de tarde.',
    autoTags: ['anotacoes', 'foto'],
  },
  'consulta': {
    id: 'consulta',
    label: 'Consulta Médica',
    timeRange: '09h',
    day: 'semana',
    dayLabel: '12 de maio',
    summary: 'Receita recebida por email após consulta.',
    autoTags: ['saude_2024', 'receita'],
  },
  'financas': {
    id: 'financas',
    label: 'Finanças do mês',
    timeRange: '20h',
    day: 'semana',
    dayLabel: '10 de maio',
    summary: 'Atualização da planilha mensal de gastos.',
    autoTags: ['fatura'],
  },
};

// Day groupings ─────────────────────────────────────────
const DAYS = [
  {
    id: 'hoje',
    title: 'Hoje',
    subtitle: 'segunda · 20 de maio · 2024',
    sessions: ['exames-manha', 'pesquisa-tarde'],
  },
  {
    id: 'ontem',
    title: 'Ontem',
    subtitle: 'domingo · 19 de maio · 2024',
    sessions: ['manha-celular', 'tarde-quadro'],
  },
  {
    id: 'semana',
    title: 'Esta semana',
    subtitle: '12 — 18 de maio · 2024',
    sessions: ['consulta', 'financas'],
  },
];

// All known tags (for sidebar) ──────────────────────────
const ALL_TAGS = [
  'artigo_academico', 'estudos', 'ux', 'hci',
  'comprovante', 'fatura', 'energia',
  'saude_2024', 'laboratorio', 'exame_sangue',
  'anotacoes', 'foto', 'grafico_dados',
];

Object.assign(window, { FILES, SESSIONS, DAYS, ALL_TAGS, TAGS, tagMeta });
